using Radzen;
using SalesAuto.Models;
using SalesAuto.Models.Entities;
using SalesAuto.Models.SearchModel;
using SalesAuto.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace SalesAuto.Wasm.Services
{
    public interface IABRClient
    {
        Task<List<ABRDanhMuc>> GetDanhMucABR();
        Task<List<ABRCongViecHisVM>> GetDanhMucCongViecHis();
        Task<List<ABRNhom>> GetNhomABR();
        Task<bool> SaveDanhMucABR(ABRDanhMuc aBRDanhMuc);
        Task<bool> DeleteDanhMucABR(int iD);
        Task<ABRMapCongViecABRHIS> SaveMapCongViecABRHIS(ABRMapCongViecABRHIS item);
        Task<bool> DeleteMapCongViecABRHIS(int iD);
        Task<List<ABRMapCongViecABRHISVM>> GetDanhSachMapCongViecABRHIS();
        Task<List<ABRNhanVien>> LayDanhSachABRNhanVien();
        Task<bool> SaveABRNhanVien(ABRNhanVien item);
        Task<bool> DeleteABRNhanVien(Guid iD);
        Task<List<ABRMapNhanVienABRHISVM>> GetDanhSachMapNhanVienABRHIS();
        Task<bool> SaveMapNhanVienABRHIS(ABRMapNhanVienABRHISVM item);
        Task<bool> DeleteMapNhanVienABRHIS(Guid iD);
        Task<List<AbrNhanVienHisVM>> LayDanhSachNhanVienHIS();
        Task<List<ABRNhanVienThucHienVM>> GetNhanVienThucHien(NhanVienThucHienSM nhanVienThucHienSM);
        Task<bool> SaveABRNhanVienThucHien(ABRNhanVienThucHien aBRNhanVienThucHien);
        Task<bool> DeleteABRNhanVienThucHien(ABRNhanVienThucHien aBRNhanVienThucHien);
        Task<List<string>> GetNhomCongViecThongKe();
        Task<IEnumerable<IDictionary<string, object>>> GetBaoCaoChiTietDaThucHien(NhanVienThucHienSM nhanVienThucHienSM);
        Task<IEnumerable<IDictionary<string, object>>> GetBaoDaThucHien(NhanVienThucHienSM nhanVienThucHienSM);
        Task<bool> ABRSaveDanhGiaNhanVien(ABRDanhGiaNhanVien aBRDanhGiaNhanVien);
        Task<List<AbrPool>> GetDanhSachPool();
        Task<List<AbrPool>> GetNhanVienHuongPool(Guid IDABRNhanVien);
        Task<bool> AddNhanVienHuongPool(Guid IDABRNhanVien, Guid IDABRPool);
        Task<bool> DeleteNhanVienHuongPool(Guid IDABRNhanVien, Guid IDABRPool);
        Task<List<AbrSoSanhChiTietVM>> GetABRSoSanhChiTiet(int thang, int nam, string MaBenhVien);
        Task<List<ABRSoSanhTongHopVM>> GetABRSoSanhTongHop(int thang, int nam, string MaBenhVien);
        Task<List<ABRSoSanhTongHopVM>> GetABRDoanhThuThangTongHop(int thang, int nam, string MaBenhVien);
        Task<bool> SaveXetDuyet(int Thang, int Nam, int Muc, List<ABRSoSanhTongHopVM> listTongHop);
        Task<bool> DeleteXetDuyet(int Thang, int Nam, int Muc, string MaBenhVienChiNhanh = "");
        Task<bool> CheckDaTinhSoLuongABR(int Thang, int Nam);
        Task<bool> CheckDaUploadBangDanhGia(int Thang, int Nam);
        Task<bool> CheckDaTinhABR(int Thang, int Nam);
        Task<bool> CheckDaXetDuyet(int Thang, int Nam, int Muc, string MaBenhVienChiNhanh);
        Task<List<ABRDanhGiaNhanVien>> GetBangDanhGiaNhanVien(int thang, int nam);
        Task<bool> DeleteBangDanhGiaNhanVien(int thang, int nam);
        Task<bool> TinhHuongABR(int Thang, int Nam);
        Task<List<ABRNganSachThang>> GetNganSachThang(int thang, int nam, string MaBenhVienChiNhanh = "");
        Task<bool> SaveNganSachThang(ABRNganSachThang item);
        Task<int> GetSoLanTuChoi(int Thang, int Nam, int Muc);
        Task<List<ABRDieuChinh>> GetABRDieuChinh(int thang, int nam);
        Task<bool> SaveABRDieuChinh(ABRDieuChinh item);
        Task<List<ABRChiTietNhanVienVM>> GetABRChiTietNhanVien(string MaNhanVien, int thang, int nam);
        Task<List<ABRThucHienCuoiVM>> GetThucHienCuoi();
        Task<IEnumerable<IDictionary<string, object>>> GetLuongNhomDichVu(int thang, int nam);
        Task<IEnumerable<IDictionary<string, object>>> GetLuongChiTietDichVu(int thang, int nam);
        Task<bool> AddNhanVienABRLuonDuocHuong(Guid IDABRNhanVien, int IDABRDanhMuc);
        Task<bool> DeleteNhanVienABRLuonDuocHuong(Guid IDABRNhanVien, int IDABRDanhMuc);
        Task<List<ABRDanhMuc>> GetNhanVienABRLuonDuocHuong(Guid IDABRNhanVien);
        Task<ABRHuongBacThang> SaveHuongBacThang(ABRHuongBacThang aBRHuongBacThang);
        Task<bool> DeleteHuongBacThang(Guid ID);
        Task<List<ABRHuongBacThang>> GetDanhSachHuongBacThang(int IDABRDanhMuc);
        Task<List<ABRLoaiVaiTro>> GetDanhSachLoaiVaiTro();
        Task<bool> DeletePool(Guid ID);
        Task<AbrPool> SavePool(AbrPool aBRPool);
        Task<ABRThangNam> GetNgayTheoThang(int Thang, int Nam);
        Task<ABRThangNam> SaveNgayTheoThang(ABRThangNam item);
        Task<IEnumerable<IDictionary<string, object>>> GetNhanVienThucHienHis(NhanVienThucHienSM nhanVienThucHienSM);
        Task<List<AbrPool>> GetPoolHuongTheoDanhMuc(int idDanhMuc);
        Task<bool> DeletePoolHuongTheoDanhMuc(int idDanhMuc);
        Task<bool> SavePoolHuongTheoDanhMuc(int idDanhMuc, Guid idPool);
        Task<List<ABRDanhMucNhanVienVM>> GetDanhSackDanhMucNhanVien(Guid IDNhanVien);
        Task<ABRDanhMucNhanVienVM> SaveDanhMucNhanVien(ABRDanhMucNhanVienVM aBRDanhMucNhanVienVM);
        Task<bool> DeleteDanhMucNhanVien(ABRDanhMucNhanVienVM aBRDanhMucNhanVienVM);
        Task<bool> CheckDaXetDuyetTheoNgay(DateTime Ngay,string MaBenhVienChiNhanh="");
        Task<List<ABRDanhMuc>> GetDanhMucABRMasterData();
        Task<bool> SaveDanhMucABRMasterData(ABRDanhMuc aBRDanhMuc);
        Task<bool> DeleteDanhMucABRMasterData(int iD);
        Task<List<ABRDanhMucXetDuyet>> GetDanhMucXetDuyet();
        Task<List<ABRDanhMucXetDuyet>> GetDanhMucXetDuyetMaster();
        Task<ABRDanhMucXetDuyet> SaveTinhTrangXetDuyetMaster(ABRDanhMucXetDuyet aBRDanhMucXetDuyet);
        Task<List<ABRXacNhanNhanVienThucHienHisVM>> GetXacNhanNhanVienThucHienHis(DateTime TuNgay, DateTime DenNgay);
        Task<ABRXacNhanNhanVienThucHienHisVM> SaveXacNhanNhanVienThucHienHis(ABRXacNhanNhanVienThucHienHisVM item);
        Task<bool> DeleteXacNhanNhanVienThucHienHis(ABRXacNhanNhanVienThucHienHisVM item);
        Task<List<UserVM>> LayUserKetThucHis();
        Task<List<ABRUserKetThucCongViecHisVM>> GetUserKetThucCongViecHis();
        Task<ABRUserKetThucCongViecHis> SaveUserKetThucCongViecHis(ABRUserKetThucCongViecHis item);
        Task<bool> DeleteUserKetThucCongViecHis(Guid ID);
        Task<List<ABRNgayCong>> GetNgayCong(int Thang, int Nam);
        Task<ABRNgayCong> SaveNgayCong(ABRNgayCong item);
        Task<bool> DeleteNgayCong(ABRNgayCong item);
        Task<IEnumerable<IDictionary<string, object>>> GetBaoCaoXacNhanNhanVienHis(DateTime TuNgay, DateTime DenNgay);
        Task<IEnumerable<IDictionary<string, object>>> GetBaoCaoChiTietXacNhanNhanVienHis(DateTime TuNgay, DateTime DenNgay);
        Task<List<BenhVienVM>> GetBenhVien();
        Task<List<ABRUserXacNhanNoiLamViec>> GetUserXacNhanNoiLamViecThucHien();
        Task<ABRUserXacNhanNoiLamViec> SaveUserXacNhanNoiLamViecThucHien(ABRUserXacNhanNoiLamViec aBRUserXacNhanNoiLamViec);
        Task<bool> DeleteUserXacNhanNoiLamViecThucHien(ABRUserXacNhanNoiLamViec aBRUserXacNhanNoiLamViec);
        Task<List<ABRUserXacNhanNoiLamViec>> GetUserXacNhanNoiLamViecChiDinh();
        Task<ABRUserXacNhanNoiLamViec> SaveUserXacNhanNoiLamViecChiDinh(ABRUserXacNhanNoiLamViec aBRUserXacNhanNoiLamViec);
        Task<bool> DeleteUserXacNhanNoiLamViecChiDinh(ABRUserXacNhanNoiLamViec aBRUserXacNhanNoiLamViec);
        Task<List<ABRNoiLamViecVM>> GetNoiLamViec();
        Task<List<ABRSoSanhTongHopVM>> GetABRDieuChinhThangTongHop(int thang, int nam, string MaBenhVienChiNhanh);
    }
}